### ISSUE TITLE
Question about DRM criteria

### ISSUE THREAD

**Issue by markloyman** [jovanavidenovic/DAM4SAM#4]
> A bounding box is fitted to the output mask and to the union of the output mask and the largest connected component in the alternative mask. If the ratio between the area of the two bounding boxes drops below θanc = 0.7, the current frame is considered as a potential candidate to update DRM.

Hi, can you please explain the rationale behind this criteria? It seems to imply that distractors are imprortant when they are far from the real object. Not sure why this is the case.

Have you tested other criteria (for example IoU score of the alternatice candidates)?

**Comment by alanlukezic** [comment]
Hi, your observation is correct - the criterion in general really implies that distractors far away are more important. However, since the threshold is relatively large (0.7), the distractor detection is triggered quite quickly. Such a criterion is a bit more sensitive to distractors, compared to the mask-to-mask IoU. This is a general idea behind the criteria, but maybe @jovanavidenovic has any additional insight behind this design choice. 
In the future we plan to invest some effort into this simple distractor detection rule and try to find some more principled formulation of such events.
