### ISSUE TITLE
How to get test results using my custom video file?

### ISSUE THREAD

**Issue by BupyeongHealer** [jovanavidenovic/DAM4SAM#6]
Thanks for sharing great work.

I want to use your model using my custom video file like test.mp4.
Can I know how to get test results?
Due to my storage size, I can't download DiDi dataset.
However, 'run_on_didi.py' file need to download DiDi dataset. (I can't know data structure in DiDi.)

I want to know easy way to get test results using your model.

Best regards,
Minseok

**Comment by alanlukezic** [comment]
Hi, we just provided an example which runs the tracker on an arbitrary sequence of images. The example loads the images from the given folder, asks user to draw a bounding box, which is then used to estimate init segmentation mask and then the tracker is used for frame-by-frame tracking. It can be run as:
CUDA_VISIBLE_DEVICES=0 python run_bbox_example.py --dir <path_to_frames_directory>
optionally, you can use --ext <extension> to determine extension of frames, e.g., jpg, png, etc. (default is jpg)
you can also use the --output_dir <output_directory_path>, which is used to specify the directory where output masks will be saved. If not specified the script will visualize the results. 
If you would like to run it on a .mp4 video, you can simply modify the script to read the frames from the video file instead of a directory.

**Comment by BupyeongHealer** [comment]
Many thanks for uploading code.
Now, I got a great results!
Have a good day~
